In [1]:
import numpy as np
import pandas as pd
##_____________________________

# make_data_set 함수: csv 파일을 numpy로 반환 
def make_data_set(num_features, act, trial, sub_id):
    data_set = np.zeros((0, num_features))
    fname = 'A_DeviceMotion_data/' + act + '_' + str(trial) + '/sub_' + str(sub_id)+'_comp.csv' # 압축한 파일을 불러오도록 설정
    raw_data = pd.read_csv(fname)
    raw_data = raw_data.drop(['Unnamed: 0'], axis=1)
    unlabel_data = raw_data.values
    data_set = np.append(data_set, unlabel_data, axis = 0)
    return data_set, list(raw_data.columns)
#________________________________

# bdi_uncomp 함수: BDI로 압축 해제한 numpy를 반환
def bdi_uncomp(after_bdi):
    bdi = after_bdi

    ## base와 immediate로 원본값 복구, base 삭제
    for i in range(bdi.shape[1]):
        for j in range(bdi.shape[0] - 1):
            bdi[j, i] = bdi[-1, i] + bdi[j, i]
    bdi = np.delete(bdi, -1, axis=0)

    ## 정수형(int)으로 변환했던 값을 다시 소수형(float)으로
    bdi = bdi / 1000000

    return bdi
#________________________________

print("--> Start...")
## 불러올 csv 파일의 이름 및 위치를 정한다
num_features = 12 # attitude(roll, pitch, yaw); gravity(x, y, z); rotationRate(x, y, z); userAcceleration(x,y,z)
act = "dws" # dws, ups, wlk, jog, sit, std
trial = 1 # 0 ~ 16
sub_id = 1 # 1 ~ 24

## make_data_set으로 csv 파일을 ds 변수에 저장
print("--> CSV to Numpy data set")
ds, columns_list = make_data_set(num_features, act, trial, sub_id)
print("--> Numpy data set shape:", ds.shape)
print(ds)

# bdi_uncomp로 BDI 압축 해제
print("--> BDI Uncompression Start")
raw_ds = bdi_uncomp(ds)
print("--> Numpy data set shape:", raw_ds.shape)
print(raw_ds)

## numpy를 csv 파일로 저장
print("--> Numpy to CSV")
pd.DataFrame(raw_ds).to_csv('A_DeviceMotion_data/' + act + '_' + str(trial) + '/sub_' + str(sub_id)+'_uncomp.csv', header=columns_list, index=1)

--> Start...
--> CSV to Numpy data set
--> Numpy data set shape: (1752, 12)
[[ 134927.  -42927.  693436. ...  113816. -591585.  458060.]
 [ 134787.  -26018.  674826. ...   38327. -371247.  195384.]
 [ 134560.  -16029.  668015. ... -170364. -272391.  -87289.]
 ...
 [ 456352.  104007. 2436522. ... -229183. -377537.  140958.]
 [ 476170.   94186. 2430839. ... -246089. -449667.  126569.]
 [1393205. -690969.    2936. ...  181078.  407092.  -80518.]]
--> BDI Uncompression Start
--> Numpy data set shape: (1751, 12)
[[ 1.528132 -0.733896  0.696372 ...  0.294894 -0.184493  0.377542]
 [ 1.527992 -0.716987  0.677762 ...  0.219405  0.035845  0.114866]
 [ 1.527765 -0.706998  0.670951 ...  0.010714  0.134701 -0.167807]
 ...
 [ 1.830821 -0.578367  2.447967 ... -0.08559  -0.030208 -0.08774 ]
 [ 1.849557 -0.586962  2.439458 ... -0.048105  0.029555  0.06044 ]
 [ 1.869375 -0.596783  2.433775 ... -0.065011 -0.042575  0.046051]]
--> Numpy to CSV
